### ISSUE TITLE
[BUG]: Redundant registration error

### ISSUE THREAD

**Issue by Servinjesus1** [Falcion/UnitadeOBSIDIAN#5]
### Contact details

@Servinjesus1

### What the essence of the bug

Registering the same extension twice by different plugins can cause issues. I just ran into this with both `txt to md` and `ini-obsidian` installed along with Unitade. If these register editors before Unitade, then Unitade breaks.

Not extremely critical, mostly user-proofing in case users accidentally add extensions to Unitade or use multiple plugins to do similar things.

### Version of an app

1.3.7

### On what OS you have encountered the bug.

macOS

### Code of conduct

- [X] I agree to follow this project's code of conduct

### Issue policy

- [X] I agree to follow this project's issue policy

**Comment by Falcion** [comment]
As I checked the projects READMEs, you can called them obsolete, but I think it is "possible" to add the "incompatibility" message when you install both of this plugins, or in extreme cases add integrations with them.

On my system, (win-app-v1.4.16) there was no errors and issues, can you provide more advanced context about which you encountered?

And thanks for the issue.

**Comment by Servinjesus1** [comment]
Actually, deathau has archived both his plugins and pointed them directly to yours, so this issue is no longer relevant!

Hopefully this gives your plugin more traction! Looking forward to where this goes!
