### ISSUE TITLE
This plugins does not support your device (iOS)

### ISSUE THREAD

**Issue by suckerSlayer** [Falcion/UnitadeOBSIDIAN#6]
Tried install it from Obsidian(iOS), but be prompted with "not support". is it possible to support on iOS device?

**Comment by Falcion** [comment]
Current version of the plugin contains in its public version only the version for desktop PCs, however, in the next version I plan to change this parameter, opening access to the plugin also on mobile devices.

- shortly, yes, and it planned, but testing will be on the side of the community.

Extra thanks for the issue!

**Comment by Falcion** [comment]
Changed manifesto of this plugin, now the plugin should be available on all platforms, in case of bugs, errors, problems, create an issue.

https://github.com/Falcion/UnitadeOBSIDIAN/blob/03e30a7352e8f0b3df99b5ccf9414a2c31301766/manifest.json#L9C8-L9C8

Closing due new update of plugin.
